### ISSUE TITLE
Discord.js@12

### ISSUE THREAD

**Issue by Timong-craft** [AlthalusAvan/discord-minecraft-whitelist#14]
Can you please make a version with discord.js@13?
Becorse https://github.com/discord/discord-api-docs/discussions/4510

**Comment by AlthalusAvan** [comment]
This project is deprecated - if you need an updated version, you'll need to fork the repo and make the required changes yourself.

**Comment by Timong-craft** [comment]
And why is the repository not in the deprecated mode?
